/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/MaleHead.glb -o src/components/MaleHead.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MaleHead(props) {
  const { nodes, materials } = useGLTF('/models/MaleHead.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eyeball_m.geometry} material={materials.Default} />
      <mesh geometry={nodes.Head_male.geometry} material={materials['Default-2']} />
    </group>
  )
}

useGLTF.preload('/models/MaleHead.glb')
